# Generated by Django 5.2.4 on 2025-10-14 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='de_ame',
            new_name='dep_name',
        ),
    ]
